### PR TITLE
Add: G2U use case diagram

### PR DESCRIPTION
**Pull request by TeeThanakit**
## Description
This pull request adds the following:  
1. A **use case diagram** for the G2U application that highlights key functionalities:
   - Browsing products and viewing product details.
   - Managing user profiles, linked products and my purchase.
   - Handling user posts for "Want-to-Buy" and "Want-to-Sell."
   - Linking with a payment gateway for processing transactions.

## Feedback Request
I would appreciate your feedback on the following aspects:
1. **Clarity**: Are the actors and use cases well-defined and easy to understand?  
2. **Completeness**: Does the diagram adequately cover all user interactions for the G2U application?  
3. **Structure**: Is the flow logical and well-organized? Are there ways to improve grouping or relationships between use cases?

Current diagram: [Click here](//www.plantuml.com/plantuml/png/VP71ghCm48NtUOh1lPl_0NwARN5J8T1hknvqseR61989HIxttM-Jg62Hkv7np3USmydECpeEWnQQRWnimQdxWw5NZZfMrWY17Li7nJvujWEv0j33VbObZWCPXXgPNZYcfQo5YDTexfgWgF-r1NmB083WgKF_rYfdNvv0Ejk7Zdqwg-IQkIXwpGGSY57f35xaOKqsQF1Eq7foyU2cD2MmbMlks2jU0SSjovCoJ-hNsKvRO3E23Avxl9Kvs6OkQJrdeFa0uWQkQBXaMrOXrtVzglwWpgJrX9q_tPu42DEBJ7uuYXyXzb2M_sF1bKnJR32BiQCsYyTbEgKfWnCNepTPY_cMyRpierNyf3zPYnsPFWpw5m00)

### CODE REVIEW

**Review by YuilTripathee — COMMENTED** [review]
Please make aliases in readable short forms (abbreviations are too short), making us having to go back and forth.

Then, rename the file as `10_usecase_overall.puml`.

1 -> represents type (1 for use case, 2 for class, 3 for sequence)
Following 0 -> represents serial number (in case we have to add more use case diagrams).

**Comment by YuilTripathee** [comment]
Also, provide the context where customer has two roles as buyers or sellers. Kinda like inheritance concept in OOP.

**Comment by TeeThanakit** [comment]
> Also, provide the context where customer has two roles as buyers or sellers. Kinda like inheritance concept in OOP.

Fixed

Current diagram: [Click here](https://www.plantuml.com/plantuml/png/VPF1QiCm38RlVWgHUovxW57AHYyh1BPkPvEehQbhWwrGmjYxptBjePYoKwFl_uGSAzr4qe7cgrKMZmJa8PZJcM0o0KSotYcbH_81kksyOEX0HyXF5R-ZjONV7simwEMAZc2d2MzwoKPX1Id5CxGxMOHkztJeu5i10CmHHnqJsmP_Ixz3yDCyKhmFpwoWjVvfy5PbU47InjvxE7ZOSOWOkEDeB6QJGQdNvkjaQ6Ko46PpYZVZBZYjJbvOHG-QzWiCSnZFYUIE16hTw7ljz0bXy96AcG7NZSa8lhIZddoV5iTshZzyglvnUPb2vh8zmmL1rvLcbL6frOzI-Jlf--TcPna3St7RWiftKJptWLrngwycvLZkNWatPU8Uca2yin9Z8MND5fjKVXLD99Uf_YPp8gzDF7FK_64swARvQdy1)

**Review by YuilTripathee — COMMENTED** [review]
Prefer adding new line at the end of file.

**Comment by TeeThanakit** [comment]
> Prefer adding new line at the end of file.

added

I have made some changes on diagram.
- Add delete and update use case
- Group WTB and WTS use case together

Click here to view more: [This one is better](//www.plantuml.com/plantuml/png/VPF1QiCm343l_WgHUoxxW55AHoyh1BPkPvEehQaR5rkXXB5_Nwmucsp2Jh6Udh1SgPj0sjDmiyhYYO0SU7E-47J6Oql6zKhfbfo7QZkCw2lG0VYqu3UqDl7vk2GQFTwm9zXhmeSUsKWi8QNY7Re_MuHg_tIiu4i100m1MnqcjlNkCNqRxxgXfJ1VpYoXNFym-5Xas25fO-UQc5YjE0RqiU9aBB8PGOfpywKpb9aH2BFeujLSiSiRPxIGbPB32CtWsyj4k602Irpe1zthCqBZ0YMJGOmBCoBur3tLvEhjm4FW-DrDqJzk7AMGOrZsS4NGoq1PZIZ5kRj3YuHmTs4MEUPsYsdSEoqzZbUyluVpINqhnIjPry_5UZ26oCLW1PK_d8gFNB4NNEhPJPoMQwQKa3ahNbsav4FBLBgCFrCiXbSW7f4IZSVoREVAfDZWCYLNJ_rUoHanP76EgUBFlS6-6sxs1m00)

**Comment by YuilTripathee** [comment]
LGTM now

**Comment by TeeThanakit** [comment]
thank you for your time and assistance

**Pull request merged**
